### ISSUE TITLE
redirect www.biocaching.com/* to biocaching.com/*

### ISSUE THREAD

**Issue by Abbe98** [Biocaching/issues#12]
Currently both www.biocaching.com and biocaching.com works but login sessions is not shared in between them. They also introduces a diversity in URLs.

I suggest redirecting all www.biocaching.com/* requests to biocaching.com/*.

**Comment by bjornhjelle** [comment]
Will look into this when time allows. 
https://www.digitalocean.com/community/tutorials/how-to-redirect-www-to-non-www-with-apache-on-ubuntu-14-04

**Comment by Abbe98** [comment]
Actually the Digitalocean article suggest it's not possible to do it on DNS settings level and I think I enabled `.htaccess` files at one point, so I'm assigning this to myself.

**Comment by Abbe98** [comment]
Done

**Comment by pbb72** [comment]
Shouldn't it be the other way around really? domain.com is the more general name, while www.domain.com is specifically the webserver. (As opposed to ftp.domain.com, smtp.domain.com, etc.) Requests to the general name get redirected to the webserver name.

**Comment by Abbe98** [comment]
@pbb72 usually that's the case yes, but most people rely don't think of sub-domains that way. It makes sense for you and me, the thing that differs for the user is shorter URLs.

**Comment by pbb72** [comment]
For the user it doesn't matter which way around it is, because they are being redirected. So they can just use the shorter URL regardless of the configuration 😉
